### ISSUE TITLE
Slide(s) discussing dtype overhaul

### ISSUE THREAD

**Issue by rossbar** [BIDS-numpy/presentation-uofm-2020#3]
I have one cell (== slide in RISE) near the end dedicated to the overhaul of the dtype system. Right now, the only thing I have in there is a few high-level sentences that I gathered from the draft NEP. 

The first question is: do you want this brought up at all? If you don't think this is ready for discussion (or not audience-appropriate) I'm happy to skip over it in the presentation. If you do want a dtype discussion included, is there anything you'd like to add change? Any examples and/or graphics that you think are relevant?

**Comment by seberg** [comment]
I think some high level statements are the only thing you can easily do, everything else derails way too quickly into something that is either not helpful or technical (why would they care if the NumPy internals are more sensible).

Overall, I think mentioning it is good, but I am not sure if you want to mention "technical" things at all. I have the graphic you probably saw about the dtype hierarchy, but I doubt you want to explain that in detail(?) so not sure that is helpful.

Improve NumPy maintainability:
  * Disentangle individual datatypes
  * Use the same API internally and for user dtypes
  * Enable easier API additions and changes in the future

User Impact:
  * Allow users to define new dtypes easier, including from Python
  * Enable the ecosystem to create `dtypes` such as:
    * physical units
    * categoricals
    * `bfloat16`, `int24`, …
    * IP-Addresses.

I like the units example (even if `astropy.units`, etc. exist).

Does this help you? If you want to keep it short, just mentioning we are working on revamping the DTypes to allow things like "list of dtypes" seems fine to me.

**Comment by rossbar** [comment]
Thanks @seberg that is indeed very helpful. I like the breakdown along the lines of "internals" and "user impact" - I will re-formulate the slide to use it. Thanks again for the input!
